In [1]:
!pip install polars

Collecting polars
  Downloading polars-1.38.1-py3-none-any.whl.metadata (10 kB)
Collecting polars-runtime-32==1.38.1 (from polars)
  Downloading polars_runtime_32-1.38.1-cp310-abi3-macosx_10_12_x86_64.whl.metadata (1.5 kB)
Downloading polars-1.38.1-py3-none-any.whl (810 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 810.4/810.4 kB 3.0 MB/s  0:00:00m 7.2 MB/s eta 0:00:01
Downloading polars_runtime_32-1.38.1-cp310-abi3-macosx_10_12_x86_64.whl (44.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 MB 6.1 MB/s  0:00:07 eta 0:00:01[36m0:00:01
Installing collected packages: polars-runtime-32, polars
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [polars]━━━━ 1/2 [polars]
Successfully installed polars-1.38.1 polars-runtime-32-1.38.1

In [2]:
import polars as pl

In [3]:
insurance = pl.read_csv(r"/Users/bilegjargalbattulga/Desktop/data analyst/Python for Dana Analysis/Polars/health_insurance.csv")

In [4]:
insurance

shape: (1_338, 7)
┌─────┬────────┬────────┬──────────┬────────┬───────────┬─────────────┐
│ age ┆ sex    ┆ bmi    ┆ children ┆ smoker ┆ region    ┆ charges     │
│ --- ┆ ---    ┆ ---    ┆ ---      ┆ ---    ┆ ---       ┆ ---         │
│ i64 ┆ str    ┆ f64    ┆ i64      ┆ str    ┆ str       ┆ f64         │
╞═════╪════════╪════════╪══════════╪════════╪═══════════╪═════════════╡
│ 19  ┆ female ┆ 27.9   ┆ 0        ┆ yes    ┆ southwest ┆ 16884.924   │
│ 18  ┆ male   ┆ 33.77  ┆ 1        ┆ no     ┆ southeast ┆ 1725.5523   │
│ 28  ┆ male   ┆ 33.0   ┆ 3        ┆ no     ┆ southeast ┆ 4449.462    │
│ 33  ┆ male   ┆ 22.705 ┆ 0        ┆ no     ┆ northwest ┆ 21984.47061 │
│ 32  ┆ male   ┆ 28.88  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   │
│ …   ┆ …      ┆ …      ┆ …        ┆ …      ┆ …         ┆ …           │
│ 50  ┆ male   ┆ 30.97  ┆ 3        ┆ no     ┆ northwest ┆ 10600.5483  │
│ 18  ┆ female ┆ 31.92  ┆ 0        ┆ no     ┆ northeast ┆ 2205.9808   │
│ 18  ┆ female ┆ 36.85  ┆ 0        ┆ no     ┆ southeast ┆ 1629.8335   │
│ 21  ┆ female ┆ 25.8   ┆ 0        ┆ no     ┆ southwest ┆ 2007.945    │
│ 61  ┆ female ┆ 29.07  ┆ 0        ┆ yes    ┆ northwest ┆ 29141.3603  │
└─────┴────────┴────────┴──────────┴────────┴───────────┴─────────────┘

shape: (1_338,)
Series: 'smoker' [str]
[
	"yes"
	"no"
	"no"
	"no"
	"no"
	…
	"no"
	"no"
	"no"
	"no"
	"yes"
]

In [12]:
#insurance['smoker'] in pandas
insurance.select(pl.col('*'))

shape: (1_338, 7)
┌─────┬────────┬────────┬──────────┬────────┬───────────┬─────────────┐
│ age ┆ sex    ┆ bmi    ┆ children ┆ smoker ┆ region    ┆ charges     │
│ --- ┆ ---    ┆ ---    ┆ ---      ┆ ---    ┆ ---       ┆ ---         │
│ i64 ┆ str    ┆ f64    ┆ i64      ┆ str    ┆ str       ┆ f64         │
╞═════╪════════╪════════╪══════════╪════════╪═══════════╪═════════════╡
│ 19  ┆ female ┆ 27.9   ┆ 0        ┆ yes    ┆ southwest ┆ 16884.924   │
│ 18  ┆ male   ┆ 33.77  ┆ 1        ┆ no     ┆ southeast ┆ 1725.5523   │
│ 28  ┆ male   ┆ 33.0   ┆ 3        ┆ no     ┆ southeast ┆ 4449.462    │
│ 33  ┆ male   ┆ 22.705 ┆ 0        ┆ no     ┆ northwest ┆ 21984.47061 │
│ 32  ┆ male   ┆ 28.88  ┆ 0        ┆ no     ┆ northwest ┆ 3866.8552   │
│ …   ┆ …      ┆ …      ┆ …        ┆ …      ┆ …         ┆ …           │
│ 50  ┆ male   ┆ 30.97  ┆ 3        ┆ no     ┆ northwest ┆ 10600.5483  │
│ 18  ┆ female ┆ 31.92  ┆ 0        ┆ no     ┆ northeast ┆ 2205.9808   │
│ 18  ┆ female ┆ 36.85  ┆ 0        ┆ no     ┆ southeast ┆ 1629.8335   │
│ 21  ┆ female ┆ 25.8   ┆ 0        ┆ no     ┆ southwest ┆ 2007.945    │
│ 61  ┆ female ┆ 29.07  ┆ 0        ┆ yes    ┆ northwest ┆ 29141.3603  │
└─────┴────────┴────────┴──────────┴────────┴───────────┴─────────────┘

In [16]:
#create a new column

insurance_month = insurance.with_columns((pl.col('charges')/12).alias('charges_per_month'))