In general:
- Merge uses columns
- Join uses the indexes

In [1]:
import pandas as pd

In [17]:
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]
}

df1 = pd.DataFrame(data1)

data2 = {
    'emp_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 'Accounting', 'Accounting', 'Sales', 'Sales']
}

df2 = pd.DataFrame(data2)

In [3]:
df1

   employee_id            name                          job_title  salary
0            1   Michael Scott                   Regional Manager  100000
1            2     Jim Halpert               Sales Representative   60000
2            3      Pam Beesly                       Receptionist   55000
3            4  Dwight Schrute  Assistant to the Regional Manager   65000
4            5   Angela Martin                 Head of Accounting   60000
5            6    Kevin Malone                         Accountant   55000
6            7  Oscar Martinez                         Accountant   55000
7            8  Stanley Hudson               Sales Representative   60000

In [4]:
df2

   employee_id            name  department
0            1   Michael Scott  Management
1            2     Jim Halpert       Sales
2            3      Pam Beesly   Reception
3            5   Angela Martin  Accounting
4            6    Kevin Malone  Accounting
5            7  Oscar Martinez  Accounting
6            8  Stanley Hudson       Sales
7            9   Phyllis Vance       Sales

In [8]:
df1.merge(df2) # default performing automatically inner join
# but better to specify

   employee_id            name             job_title  salary  department
0            1   Michael Scott      Regional Manager  100000  Management
1            2     Jim Halpert  Sales Representative   60000       Sales
2            3      Pam Beesly          Receptionist   55000   Reception
3            5   Angela Martin    Head of Accounting   60000  Accounting
4            6    Kevin Malone            Accountant   55000  Accounting
5            7  Oscar Martinez            Accountant   55000  Accounting
6            8  Stanley Hudson  Sales Representative   60000       Sales

In [10]:
df1.merge(df2, how = 'left') #on df1

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000,Management
1,2,Jim Halpert,Sales Representative,60000,Sales
2,3,Pam Beesly,Receptionist,55000,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000,NaN
4,5,Angela Martin,Head of Accounting,60000,Accounting
5,6,Kevin Malone,Accountant,55000,Accounting
6,7,Oscar Martinez,Accountant,55000,Accounting
7,8,Stanley Hudson,Sales Representative,60000,Sales

In [12]:
df1.merge(df2, how = 'right') #on df2

   employee_id            name             job_title    salary  department
0            1   Michael Scott      Regional Manager  100000.0  Management
1            2     Jim Halpert  Sales Representative   60000.0       Sales
2            3      Pam Beesly          Receptionist   55000.0   Reception
3            5   Angela Martin    Head of Accounting   60000.0  Accounting
4            6    Kevin Malone            Accountant   55000.0  Accounting
5            7  Oscar Martinez            Accountant   55000.0  Accounting
6            8  Stanley Hudson  Sales Representative   60000.0       Sales
7            9   Phyllis Vance                   NaN       NaN       Sales

In [13]:
df1.merge(df2, how = 'outer') #takes everything from both data frames and every thats similar

,employee_id,name,job_title,salary,department
0,1,Michael Scott,Regional Manager,100000.0,Management
1,2,Jim Halpert,Sales Representative,60000.0,Sales
2,3,Pam Beesly,Receptionist,55000.0,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Accounting
5,6,Kevin Malone,Accountant,55000.0,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Sales
8,9,Phyllis Vance,NaN,NaN,Sales

In [14]:
df1.merge(df2, how = 'outer', on = 'employee_id') # specify on what to join

,employee_id,name_x,job_title,salary,name_y,department
0,1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting
5,6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales
8,9,NaN,NaN,NaN,Phyllis Vance,Sales

In [15]:
df1.merge(df2, how = 'outer', on = 'employee_id') # specify on what to join

,employee_id,name_x,job_title,salary,name_y,department
0,1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN
4,5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting
5,6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting
6,7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting
7,8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales
8,9,NaN,NaN,NaN,Phyllis Vance,Sales

In [20]:
# lets change the df2.employee_id to emp_id..
# then we have to specify on which column for each dataframe using left_on and right_on

In [21]:
df1.merge(df2, how = 'outer', left_on = 'employee_id', right_on = 'emp_id') # specify on what to join

,employee_id,name_x,job_title,salary,emp_id,name_y,department
0,1.0,Michael Scott,Regional Manager,100000.0,1.0,Michael Scott,Management
1,2.0,Jim Halpert,Sales Representative,60000.0,2.0,Jim Halpert,Sales
2,3.0,Pam Beesly,Receptionist,55000.0,3.0,Pam Beesly,Reception
3,4.0,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN,NaN
4,5.0,Angela Martin,Head of Accounting,60000.0,5.0,Angela Martin,Accounting
5,6.0,Kevin Malone,Accountant,55000.0,6.0,Kevin Malone,Accounting
6,7.0,Oscar Martinez,Accountant,55000.0,7.0,Oscar Martinez,Accounting
7,8.0,Stanley Hudson,Sales Representative,60000.0,8.0,Stanley Hudson,Sales
8,NaN,NaN,NaN,NaN,9.0,Phyllis Vance,Sales

In [26]:
df1.join(df2, how = 'inner', lsuffix = '_df1', rsuffix = '_df2')
# gives us messy data  because it joins on indexes of df1 and df2

,employee_id,name_df1,job_title,salary,emp_id,name_df2,department
0,1,Michael Scott,Regional Manager,100000,1,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000,2,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000,3,Pam Beesly,Reception
3,4,Dwight Schrute,Assistant to the Regional Manager,65000,5,Angela Martin,Accounting
4,5,Angela Martin,Head of Accounting,60000,6,Kevin Malone,Accounting
5,6,Kevin Malone,Accountant,55000,7,Oscar Martinez,Accounting
6,7,Oscar Martinez,Accountant,55000,8,Stanley Hudson,Sales
7,8,Stanley Hudson,Sales Representative,60000,9,Phyllis Vance,Sales

In [28]:
# set_index to correct it

df1.set_index('employee_id', inplace = True)
df2.set_index('emp_id', inplace = True)

In [29]:
df1.join(df2, how = 'inner', lsuffixs = '_df1', rsuffix = '_df2')
# gives us messy data  because it joins on indexes of df1 and df2

         name_df1             job_title  salary        name_df2  department
1   Michael Scott      Regional Manager  100000   Michael Scott  Management
2     Jim Halpert  Sales Representative   60000     Jim Halpert       Sales
3      Pam Beesly          Receptionist   55000      Pam Beesly   Reception
5   Angela Martin    Head of Accounting   60000   Angela Martin  Accounting
6    Kevin Malone            Accountant   55000    Kevin Malone  Accounting
7  Oscar Martinez            Accountant   55000  Oscar Martinez  Accounting
8  Stanley Hudson  Sales Representative   60000  Stanley Hudson       Sales