Group by and Transform are really similar.

Group by groups into one row while
Transform keep all the individual rows intact, but still applies that aggregate function.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'/Users/bilegjargalbattulga/Desktop/data analyst/Python for Dana Analysis/Group By and Aggregating/banking.csv'
                , encoding = 'ISO-8859-1')

In [3]:
df

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan
0,58,management,married,tertiary,no,2143,yes,no
1,44,technician,single,secondary,no,29,yes,no
2,33,entrepreneur,married,secondary,no,2,yes,yes
3,47,blue-collar,married,unknown,no,1506,yes,no
4,33,unknown,single,unknown,no,1,no,no
...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no
45207,71,retired,divorced,primary,no,1729,no,no
45208,72,retired,married,secondary,no,5715,no,no
45209,57,blue-collar,married,secondary,no,668,no,no
45210,37,entrepreneur,married,secondary,no,2971,no,no

In [9]:
df_banking = df[:500]

In [10]:
df_banking['average_balance_per_job'] = df_banking.groupby('job')['outstanding_balance'].transform('mean')

/var/folders/mm/dk0qprd53tb6f0y8g20c97vr0000gn/T/ipykernel_61786/3318464167.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_banking['average_balance_per_job'] = df_banking.groupby('job')['outstanding_balance'].transform('mean')

In [11]:
df_banking

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,average_balance_per_job
0,58,management,married,tertiary,no,2143,yes,no,1082.815789
1,44,technician,single,secondary,no,29,yes,no,1121.407407
2,33,entrepreneur,married,secondary,no,2,yes,yes,299.714286
3,47,blue-collar,married,unknown,no,1506,yes,no,423.521429
4,33,unknown,single,unknown,no,1,no,no,18.666667
...,...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no,235.300000
496,39,blue-collar,divorced,secondary,no,42,yes,no,423.521429
497,50,blue-collar,divorced,secondary,no,41,yes,no,423.521429
498,44,blue-collar,married,secondary,no,-99,yes,no,423.521429
499,37,technician,single,secondary,no,17,yes,no,1121.407407

In [12]:
df_banking['above_below_average'] = df_banking.groupby('job')['outstanding_balance'].transform(lambda x: x-x.mean())

/var/folders/mm/dk0qprd53tb6f0y8g20c97vr0000gn/T/ipykernel_61786/962427133.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_banking['above_below_average'] = df_banking.groupby('job')['outstanding_balance'].transform(lambda x: x-x.mean())

In [13]:
df_banking

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,average_balance_per_job,above_below_average
0,58,management,married,tertiary,no,2143,yes,no,1082.815789,1060.184211
1,44,technician,single,secondary,no,29,yes,no,1121.407407,-1092.407407
2,33,entrepreneur,married,secondary,no,2,yes,yes,299.714286,-297.714286
3,47,blue-collar,married,unknown,no,1506,yes,no,423.521429,1082.478571
4,33,unknown,single,unknown,no,1,no,no,18.666667,-17.666667
...,...,...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no,235.300000,-235.300000
496,39,blue-collar,divorced,secondary,no,42,yes,no,423.521429,-381.521429
497,50,blue-collar,divorced,secondary,no,41,yes,no,423.521429,-382.521429
498,44,blue-collar,married,secondary,no,-99,yes,no,423.521429,-522.521429
499,37,technician,single,secondary,no,17,yes,no,1121.407407,-1104.407407

In [14]:
df_banking['average_balance_with_loan'] = df_banking[df_banking['housing_loan'] == 'yes'].groupby('job')['outstanding_balance'].transform(lambda x: x-x.mean())

/var/folders/mm/dk0qprd53tb6f0y8g20c97vr0000gn/T/ipykernel_61786/116084622.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_banking['average_balance_with_loan'] = df_banking[df_banking['housing_loan'] == 'yes'].groupby('job')['outstanding_balance'].transform(lambda x: x-x.mean())

In [15]:
df_banking

,age,job,marital,education,default,outstanding_balance,housing_loan,personal_loan,average_balance_per_job,above_below_average,average_balance_with_loan
0,58,management,married,tertiary,no,2143,yes,no,1082.815789,1060.184211,1115.106061
1,44,technician,single,secondary,no,29,yes,no,1121.407407,-1092.407407,-1239.102941
2,33,entrepreneur,married,secondary,no,2,yes,yes,299.714286,-297.714286,-346.636364
3,47,blue-collar,married,unknown,no,1506,yes,no,423.521429,1082.478571,1082.118110
4,33,unknown,single,unknown,no,1,no,no,18.666667,-17.666667,NaN
...,...,...,...,...,...,...,...,...,...,...,...
495,39,admin.,single,secondary,no,0,yes,no,235.300000,-235.300000,-239.616667
496,39,blue-collar,divorced,secondary,no,42,yes,no,423.521429,-381.521429,-381.881890
497,50,blue-collar,divorced,secondary,no,41,yes,no,423.521429,-382.521429,-382.881890
498,44,blue-collar,married,secondary,no,-99,yes,no,423.521429,-522.521429,-522.881890
499,37,technician,single,secondary,no,17,yes,no,1121.407407,-1104.407407,-1251.102941