# Numpy Arrays and Pandas Series

In [2]:
import numpy as np
import pandas as pd

In [3]:
my_list = [10,25,35]

In [11]:
# Creating Numpy Arrays (index is hidden)

In [4]:
x = np.array(my_list)
print(x)

[10 25 35]

In [7]:
type(x)

numpy.ndarray

In [12]:
# Creating Pandas Series (index is shown)

In [13]:
pd.Series(my_list)

0    10
1    25
2    35
dtype: int64

In [14]:
y = pd.Series(my_list)

In [15]:
type(y)

pandas.core.series.Series

In [ ]:
# In Pandas Series you can name indexes

In [17]:
index_values= ['Best', 'Second Best', 'Third Best']
my_list = [10,25,35]

one = pd.Series(data = my_list, index = index_values)

In [18]:
index_values2 = ['Best', 'Second Best', 'Forth Best']
my_list2 = [10,25,40]

two = pd.Series(data = my_list2, index = index_values2)

In [20]:
one

Best           10
Second Best    25
Third Best     35
dtype: int64

In [19]:
two

Best           10
Second Best    25
Forth Best     40
dtype: int64

In [22]:
total = one + two
total

Best           20.0
Forth Best      NaN
Second Best    50.0
Third Best      NaN
dtype: float64

In [25]:
# can refer to index using both the index name and number

In [26]:
total['Best']

20.0

In [27]:
total[0]

20.0

# Create Pandas DataFrames

In [28]:
dataframe = pd.DataFrame({'Series 1': one, 'Series 2': two})

In [29]:
print(dataframe)

             Series 1  Series 2
Best             10.0      10.0
Forth Best        NaN      40.0
Second Best      25.0      25.0
Third Best       35.0       NaN

In [30]:
dataframe

             Series 1  Series 2
Best             10.0      10.0
Forth Best        NaN      40.0
Second Best      25.0      25.0
Third Best       35.0       NaN

In [31]:
ice_cream = [['MCC', 1], ['Butterscotc', 2], ['Butter Pecan', 3]]

In [35]:
pd.DataFrame(ice_cream, index = ['Flavor 1', 'Flavor2', 'Flavor3'], columns = ('Flavor', 'Scoops') )

                Flavor  Scoops
Flavor 1           MCC       1
Flavor2    Butterscotc       2
Flavor3   Butter Pecan       3

In [36]:
pd.DataFrame(ice_cream, columns = ('Flavor', 'Scoops') )

         Flavor  Scoops
0           MCC       1
1   Butterscotc       2
2  Butter Pecan       3

In [37]:
pd.DataFrame(ice_cream)

              0  1
0           MCC  1
1   Butterscotc  2
2  Butter Pecan  3