In [17]:
import pandas as pd

# Scenario 1

In [18]:
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'full_name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Neville Longbottom', 'Ginny Weasley', 'Fred Weasley', 'George Weasley', 'Cho Chang'],
    'phone_number': ['(123) 456-7890', '555-123-4567', '9876543210', '123.456.7890', '(123)-4567890', '987-654-3210', '123 456 7890', '1234567890', '+7890123456', '012-345-6789']
}

Bad_Numbers = pd.DataFrame(data)
Bad_Numbers

   student_id           full_name    phone_number
0           1        Harry Potter  (123) 456-7890
1           2    Hermione Granger    555-123-4567
2           3         Ron Weasley      9876543210
3           4        Draco Malfoy    123.456.7890
4           5       Luna Lovegood   (123)-4567890
5           6  Neville Longbottom    987-654-3210
6           7       Ginny Weasley    123 456 7890
7           8        Fred Weasley      1234567890
8           9      George Weasley     +7890123456
9          10           Cho Chang    012-345-6789

In [19]:
Bad_Numbers['phone_number'] = Bad_Numbers['phone_number'].str.replace(r'\D', '') # a capital D looks for all the thing that are not numbers

/var/folders/mm/dk0qprd53tb6f0y8g20c97vr0000gn/T/ipykernel_65946/3918429178.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  Bad_Numbers['phone_number'] = Bad_Numbers['phone_number'].str.replace(r'\D', '') # a capital D looks for all the thing that are not numbers

In [20]:
len(Bad_Numbers[Bad_Numbers['phone_number'].str.len() != 10])

0

In [21]:
Bad_Numbers['phone_number'] = Bad_Numbers['phone_number'].str[:3] + '-' + Bad_Numbers['phone_number'].str[3:6] + '-' + Bad_Numbers['phone_number'].str[6:]

In [22]:
Bad_Numbers

   student_id           full_name  phone_number
0           1        Harry Potter  123-456-7890
1           2    Hermione Granger  555-123-4567
2           3         Ron Weasley  987-654-3210
3           4        Draco Malfoy  123-456-7890
4           5       Luna Lovegood  123-456-7890
5           6  Neville Longbottom  987-654-3210
6           7       Ginny Weasley  123-456-7890
7           8        Fred Weasley  123-456-7890
8           9      George Weasley  789-012-3456
9          10           Cho Chang  012-345-6789

# Scenario 2

In [23]:
data = {
    'Full Name': ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy', 'Luna Lovegood', 'Gregory Goyle'],
    'Voldemort_Bad': ['Y', 'Yes', 'Yes', 'No', 'yes', 'Nope!']
}

Voldy = pd.DataFrame(data)

Voldy

          Full Name Voldemort_Bad
0      Harry Potter             Y
1  Hermione Granger           Yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood           yes
5     Gregory Goyle         Nope!

In [24]:
Voldy.groupby('Voldemort_Bad').count()

               Full Name
Voldemort_Bad
No                     1
Nope!                  1
Y                      1
Yes                    2
yes                    1

In [25]:
Voldy['Voldemort_Bad'].apply(lambda x: 'Yes' if x.startswith(('Y', 'y')) else ('No' if x.startswith (('N', 'n')) else x))

0    Yes
1    Yes
2    Yes
3     No
4    Yes
5     No
Name: Voldemort_Bad, dtype: object

In [26]:
Voldy['Voldemort_Bad'] = Voldy['Voldemort_Bad'].apply(lambda x: 'Yes' if x.startswith(('Y', 'y')) else ('No' if x.startswith (('N', 'n')) else x))

In [27]:
Voldy

          Full Name Voldemort_Bad
0      Harry Potter           Yes
1  Hermione Granger           Yes
2       Ron Weasley           Yes
3      Draco Malfoy            No
4     Luna Lovegood           Yes
5     Gregory Goyle            No

# Scenario 3

In [28]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Hermione', 'Ronald', 'Harry', 'Hermion', 'Ron'],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Grangar', 'Weasly', 'Poter', 'Graner', 'Weaseley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18],
    'Social Security Number': ['123-45-6789', '987-65-4321', '555-55-5555', '987-65-4321', '555-55-5555',
                               '123-45-6789', '987-65-4321', '555-55-5555']
}

Hogwarts_Students = pd.DataFrame(data)

In [29]:
Hogwarts_Students.groupby('Social Security Number').ngroup()

0    0
1    2
2    1
3    2
4    1
5    0
6    2
7    1
dtype: int64

In [30]:
Hogwarts_Students['Same_Student_ID2'] = Hogwarts_Students.groupby('Social Security Number').ngroup()

In [32]:
Hogwarts_Students

  First Name Last Name  Age Social Security Number  Same_Student_ID2
0      Harry    Potter   18            123-45-6789                 0
1   Hermione   Granger   17            987-65-4321                 2
2        Ron   Weasley   18            555-55-5555                 1
3   Hermione   Grangar   17            987-65-4321                 2
4     Ronald    Weasly   18            555-55-5555                 1
5      Harry     Poter   18            123-45-6789                 0
6    Hermion    Graner   17            987-65-4321                 2
7        Ron  Weaseley   18            555-55-5555                 1

In [33]:
Hogwarts_Students.groupby('Same_Student_ID2')['Social Security Number'].count()

Same_Student_ID2
0    2
1    3
2    3
Name: Social Security Number, dtype: int64

In [34]:
Hogwarts_Students

  First Name Last Name  Age Social Security Number  Same_Student_ID2
0      Harry    Potter   18            123-45-6789                 0
1   Hermione   Granger   17            987-65-4321                 2
2        Ron   Weasley   18            555-55-5555                 1
3   Hermione   Grangar   17            987-65-4321                 2
4     Ronald    Weasly   18            555-55-5555                 1
5      Harry     Poter   18            123-45-6789                 0
6    Hermion    Graner   17            987-65-4321                 2
7        Ron  Weaseley   18            555-55-5555                 1

## Fuzzy matching

In [35]:
Hogwarts_Students['Name_Substring'] = Hogwarts_Students['First Name'].str[:3] + Hogwarts_Students['Last Name'].str[:3]

In [36]:
Hogwarts_Students['Same_Student_ID'] = Hogwarts_Students.groupby('Name_Substring').ngroup() + 1

In [37]:
Hogwarts_Students

,First Name,Last Name,Age,Social Security Number,Same_Student_ID2,Name_Substring,Same_Student_ID
0,Harry,Potter,18,123-45-6789,0,HarPot,1
1,Hermione,Granger,17,987-65-4321,2,HerGra,2
2,Ron,Weasley,18,555-55-5555,1,RonWea,3
3,Hermione,Grangar,17,987-65-4321,2,HerGra,2
4,Ronald,Weasly,18,555-55-5555,1,RonWea,3
5,Harry,Poter,18,123-45-6789,0,HarPot,1
6,Hermion,Graner,17,987-65-4321,2,HerGra,2
7,Ron,Weaseley,18,555-55-5555,1,RonWea,3

# Scenario 4

In [38]:
data = {
    'First Name': ['Harry', 'Hermione?', 'Ron', 'Hermione', 'Ron_', 'Harry!', 'Hermione', 'Ron'],
    'Last Name': ['"Potter"', 'Granger', 'Weasley', 'Granger', 'Weasley...', 'Potter', 'Granger', 'Weasley'],
    'Age': [18, 17, 18, 17, 18, 18, 17, 18]
}

Hogwarts_Students2 = pd.DataFrame(data)

Hogwarts_Students2

  First Name   Last Name  Age
0      Harry    "Potter"   18
1  Hermione?     Granger   17
2        Ron     Weasley   18
3   Hermione     Granger   17
4       Ron_  Weasley...   18
5     Harry!      Potter   18
6   Hermione     Granger   17
7        Ron     Weasley   18

In [41]:
Hogwarts_Students2['First Name'] = Hogwarts_Students2['First Name'].str.replace(r'[^a-zA-Z]', '', regex = True) #remove everything except a-z and A-Z

In [42]:
Hogwarts_Students2

  First Name   Last Name  Age
0      Harry    "Potter"   18
1   Hermione     Granger   17
2        Ron     Weasley   18
3   Hermione     Granger   17
4        Ron  Weasley...   18
5      Harry      Potter   18
6   Hermione     Granger   17
7        Ron     Weasley   18

In [43]:
Hogwarts_Students2['Last Name'] = Hogwarts_Students2['Last Name'].str.replace(r'[^a-zA-Z]', '', regex = True) #remove everything except a-z and A-Z

In [44]:
Hogwarts_Students2

  First Name Last Name  Age
0      Harry    Potter   18
1   Hermione   Granger   17
2        Ron   Weasley   18
3   Hermione   Granger   17
4        Ron   Weasley   18
5      Harry    Potter   18
6   Hermione   Granger   17
7        Ron   Weasley   18