In [2]:
import pandas as pd
import numpy as np

## Scenario 1

In [3]:
data = {
    'First Name': ['Harry', 'Hermione', 'Ron', 'Draco', 'Luna', np.nan, np.nan],
    'Last Name': ['Potter', 'Granger', 'Weasley', 'Malfoy', np.nan, 'Lovegood', np.nan],
    'Hogwarts House': ['Gryffindor', 'Gryffindor', 'Gryffindor', np.nan, 'Ravenclaw', 'Gryffindor', np.nan],
    'Age': [18, 17, np.nan, 16, 16, 18, np.nan]
}

Nulls = pd.DataFrame(data)

Nulls

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN   NaN

In [4]:
Nulls.dropna()

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0

In [5]:
Nulls.dropna(subset = ['Age'])

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0

In [6]:
Nulls.dropna(axis= 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [12]:
Nulls.dropna(axis = 1, subset = 3) # subset refers to row number

  First Name Last Name   Age
0      Harry    Potter  18.0
1   Hermione   Granger  17.0
2        Ron   Weasley   NaN
3      Draco    Malfoy  16.0
4       Luna       NaN  16.0
5        NaN  Lovegood  18.0
6        NaN       NaN   NaN

In [13]:
Nulls.dropna(how  = 'all')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor   NaN
3      Draco    Malfoy            NaN  16.0
4       Luna       NaN      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0

In [18]:
Nulls['Age'].fillna(Nulls['Age'].mean())

0    18.0
1    17.0
2    17.0
3    16.0
4    16.0
5    18.0
6    17.0
Name: Age, dtype: float64

### backward or forward fill

In [26]:
Nulls.fillna(method = 'ffill')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  17.0
3      Draco    Malfoy     Gryffindor  16.0
4       Luna    Malfoy      Ravenclaw  16.0
5       Luna  Lovegood     Gryffindor  18.0
6       Luna  Lovegood     Gryffindor  18.0

In [27]:
Nulls.fillna(method = 'bfill')

  First Name Last Name Hogwarts House   Age
0      Harry    Potter     Gryffindor  18.0
1   Hermione   Granger     Gryffindor  17.0
2        Ron   Weasley     Gryffindor  16.0
3      Draco    Malfoy      Ravenclaw  16.0
4       Luna  Lovegood      Ravenclaw  16.0
5        NaN  Lovegood     Gryffindor  18.0
6        NaN       NaN            NaN   NaN

In [28]:
Nulls.replace(np.nan, 'Unknown')

  First Name Last Name Hogwarts House      Age
0      Harry    Potter     Gryffindor     18.0
1   Hermione   Granger     Gryffindor     17.0
2        Ron   Weasley     Gryffindor  Unknown
3      Draco    Malfoy        Unknown     16.0
4       Luna   Unknown      Ravenclaw     16.0
5    Unknown  Lovegood     Gryffindor     18.0
6    Unknown   Unknown        Unknown  Unknown

## Scenario 2

In [30]:
data = {
    'First name': ['Harry', 'Harry', 'Hermione', 'Hermione', 'Ron', 'Ron', 'Draco', 'Draco', 'Luna', 'Luna', 'Neville', 'Neville', 'Ginny', 'Ginny', 'Fred', 'Fred', 'George', 'George', 'Cho', 'Cho', 'Cedric', 'Cedric', 'Sirius', 'Sirius', 'Remus', 'Remus'],
    'Last name': ['Potter', np.nan, 'Granger', 'Granger', 'Weasley', 'Weasley', 'Malfoy', 'Malfoy', 'Lovegood', 'Lovegood', 'Longbottom', 'Longbottom', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Weasley', 'Chang', 'Chang', 'Diggory', 'Diggory', 'Black', 'Black', 'Lupin', 'Lupin'],
    'Hogwarts house': ['Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', np.nan, 'Gryffindor', 'Slytherin', 'Slytherin', 'Ravenclaw', 'Ravenclaw', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Ravenclaw', 'Ravenclaw', 'Hufflepuff', 'Hufflepuff', 'Gryffindor', 'Gryffindor', 'Gryffindor', 'Gryffindor'],
    'Transaction_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, np.nan, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    'Transaction_amount': [50, 75, 30, 20, 45, 60, 55, 80, 65, 70, 40, 85, 90, 55, 60, 75, 80, 35, 40, 95, 50, 65, 70, 25, 30, 45]
}

df = pd.DataFrame(data)
df

   First name   Last name Hogwarts house  Transaction_ID  Transaction_amount
0       Harry      Potter     Gryffindor             1.0                  50
1       Harry         NaN     Gryffindor             2.0                  75
2    Hermione     Granger     Gryffindor             3.0                  30
3    Hermione     Granger     Gryffindor             4.0                  20
4         Ron     Weasley            NaN             5.0                  45
5         Ron     Weasley     Gryffindor             6.0                  60
6       Draco      Malfoy      Slytherin             7.0                  55
7       Draco      Malfoy      Slytherin             8.0                  80
8        Luna    Lovegood      Ravenclaw             9.0                  65
9        Luna    Lovegood      Ravenclaw            10.0                  70
10    Neville  Longbottom     Gryffindor            11.0                  40
11    Neville  Longbottom     Gryffindor            12.0                  85
12      Ginny     Weasley     Gryffindor            13.0                  90
13      Ginny     Weasley     Gryffindor            14.0                  55
14       Fred     Weasley     Gryffindor             NaN                  60
15       Fred     Weasley     Gryffindor            16.0                  75
16     George     Weasley     Gryffindor            17.0                  80
17     George     Weasley     Gryffindor            18.0                  35
18        Cho       Chang      Ravenclaw            19.0                  40
19        Cho       Chang      Ravenclaw            20.0                  95
20     Cedric     Diggory     Hufflepuff            21.0                  50
21     Cedric     Diggory     Hufflepuff            22.0                  65
22     Sirius       Black     Gryffindor            23.0                  70
23     Sirius       Black     Gryffindor            24.0                  25
24      Remus       Lupin     Gryffindor            25.0                  30
25      Remus       Lupin     Gryffindor            26.0                  45

### Cross referencing

In [38]:
df['Last name'].fillna(df.groupby(['First name', 'Hogwarts house'])['Last name'].transform('first'))

0         Potter
1         Potter
2        Granger
3        Granger
4        Weasley
5        Weasley
6         Malfoy
7         Malfoy
8       Lovegood
9       Lovegood
10    Longbottom
11    Longbottom
12       Weasley
13       Weasley
14       Weasley
15       Weasley
16       Weasley
17       Weasley
18         Chang
19         Chang
20       Diggory
21       Diggory
22         Black
23         Black
24         Lupin
25         Lupin
Name: Last name, dtype: object

In [40]:
df['Hogwarts house'].fillna(df.groupby(['First name', 'Last name'])['Hogwarts house'].transform('first'))

0     Gryffindor
1     Gryffindor
2     Gryffindor
3     Gryffindor
4     Gryffindor
5     Gryffindor
6      Slytherin
7      Slytherin
8      Ravenclaw
9      Ravenclaw
10    Gryffindor
11    Gryffindor
12    Gryffindor
13    Gryffindor
14    Gryffindor
15    Gryffindor
16    Gryffindor
17    Gryffindor
18     Ravenclaw
19     Ravenclaw
20    Hufflepuff
21    Hufflepuff
22    Gryffindor
23    Gryffindor
24    Gryffindor
25    Gryffindor
Name: Hogwarts house, dtype: object

In [43]:
df['Transaction_ID'] = df['Transaction_ID'].fillna(df['Transaction_ID'].ffill() + 1)

In [44]:
df['Transaction_ID']

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
14    15.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20    21.0
21    22.0
22    23.0
23    24.0
24    25.0
25    26.0
Name: Transaction_ID, dtype: float64